### ISSUE TITLE
Save also saves a copy in Documents

### ISSUE THREAD

**Issue by dantrueman** [Princeton-CDH/bitKlavier#100]
not sure why, but when you Save a Gallery after navigating to a directory, it also saves a copy in Documents.

**Comment by mulshine** [comment]
hmm not exactly sure what's happening. do you mean that when you "Save" in bitKlavier, it always puts a copy of the gallery in "~/Documents" as well as "~/Documents/bitKlavier resources/galleries"?

**Comment by dantrueman** [comment]
Most of the time, yes.
