### ISSUE TITLE
share not working

### ISSUE THREAD

**Issue by mulshine** [Princeton-CDH/bitKlavier#109]
:O

**Comment by dantrueman** [comment]
I think it works except for built in galleries?

miniPhone keybibbles, excuse typoibbles!

On Jul 9, 2018, at 12:20 AM, Mike Mulshine <notifications@github.com<mailto:notifications@github.com>> wrote:


:O

**Comment by mulshine** [comment]
Ohh right - I'll remove it as an option when a built-in is in use.
