### ISSUE TITLE
Synchronic envelope not working

### ISSUE THREAD

**Issue by mulshine** [Princeton-CDH/bitKlavier#113]
Can't create new envelope without it disappearing. Also, envelope greyed out even after editting.

**Comment by dantrueman** [comment]
hmmm, not sure what happened here. it worked at one point. will take a look….

On Jul 9, 2018, at 12:39 AM, Mike Mulshine <notifications@github.com<mailto:notifications@github.com>> wrote:


Can't create new envelope without it disappearing. Also, envelope greyed out even after editting.

**Comment by dantrueman** [comment]
fixed
