### ISSUE TITLE
Custom tuning menu not set properly

### ISSUE THREAD

**Issue by dantrueman** [Princeton-CDH/bitKlavier#126]
When editing a pre-existing tuning, either via text or the keyboard slider, rather than setting the scale menu to "custom" it sets it to Grammateus.

**Comment by mulshine** [comment]
Ahh ok, can imagine how this happened. When we transitions from including
adaptive's in scale menu to having them be external. Have to always
add/subtract 2 from tuning depending on menu and I think Grammateus must be
two away from Custom in the list. So this case isn't handled. In long run,
would be cleaner to re-index the scales so they are continuous.

Also I could imagine "Custom" becoming unnecessary. It could be that
offsets are saved from the current chosen scale and applied to on that
scale, and "custom" offsets notes could be highlighted slightly differently
than ones that adhere to the offsets-from-ET of the selected scale. Just a
thought.

**Comment by mulshine** [comment]
fixed with setScaleByName()
