### ISSUE TITLE
bitKlavier issues v2.4b1 (Mike)

### ISSUE THREAD

**Issue by mulshine** [Princeton-CDH/bitKlavier#132]
- [ ] Resonance samples play on non-piano sample sets / soundfonts. 
- [x] (dt): SynchronicProcessor::keyPressed crash, on line: cluster->addNote(noteNumber)
- [x] (dt): related: the blue status updates on the cluster threshold slider and other freeze instead of incrementing.
- [x] Note-length multiplier slider shows up in second tab of Nostalgic if the second tab opens first when you double-click Nostalgic prep.

**Comment by dantrueman** [comment]
i'm not getting that; i see v2.4b1. you may need to set that in Projucer, then export, since we tend to work from different Projucer files.
________________________________
