### ISSUE TITLE
Synchronic "skip first" is actually skipping two

### ISSUE THREAD

**Issue by dantrueman** [Princeton-CDH/bitKlavier#133]
make  a sequence with, say, 4 transposition. when skip first is on, it will skip the first two, and when it is off, it will skip 1

**Comment by mulshine** [comment]
hmm unless im misunderstanding, this seems to work for me (at least for
note-on first-note mode). perhaps this issue is mode-specific? do you
experience the issue in all cases?

**Comment by dantrueman** [comment]
right, ok, yes it is working, but the display is off, always ahead by one in the multisliders. for all modes
________________________________
