### ISSUE TITLE
Shared resources for distribution (e.g. Linux)

### ISSUE THREAD

**Issue by KottV** [Princeton-CDH/bitKlavier#137]
**Is your schema change related to a problem? Please describe.**
I'm packaging bitKlavier for Linux and found that not all additional resources can be found, there are only sf2 (sfz) in **Sources** and wav samples at http://manyarrowsmusic.com/bitKlavier/bitKlavier_ModelB/bitKlavier_resources.zip
While Mac and Win installer contains more stuff, like manual, preparations, pianos, scores.

So, it's not easy (or legal) to provide such bundled resources in Linux repositories.

**Proposed changes**
Add missing resources to GitHub or any other hosting. 

**Purpose**
Make distribution of bitKlavier resources more complete in Linux.

**Additional context**
Or I've just missed these links?

**Comment by dantrueman** [comment]
hello Konstantin, thanks for pointing this out. We have updated the current release announcement<https://github.com/Princeton-CDH/bitKlavier/releases/tag/2.6> with a link to the appropriate resources<https://www.dropbox.com/s/tvhad1ecsoycvx6/bK_2.6_installerResources.zip?dl=0>, and will continue to do that for future releases.

Let me know if you have further questions, and I’m glad to hear about the possible Linux package!

all best,
Dan

On Jul 28, 2020, at 10:35 PM, Konstantin Voinov <notifications@github.com<mailto:notifications@github.com>> wrote:



Is your schema change related to a problem? Please describe.
I'm packaging bitKlavier for Linux and found that not all additional resources can be found, there are only sf2 (sfz) in Sources and wav samples at http://manyarrowsmusic.com/bitKlavier/bitKlavier_ModelB/bitKlavier_resources.zip
While Mac and Win installer contains more stuff, like manual, preparations, pianos, scores.

So, it's not easy (or legal) to provide such bundled resources in Linux repositories.

Proposed changes
Add missing resources to GitHub or any other hosting.

Purpose
Make distribution of bitKlavier resources more complete in Linux.

Additional context
Or I've just missed these links?

**Comment by dantrueman** [comment]
absolutely! thanks!

On Aug 2, 2020, at 12:19 AM, Konstantin Voinov <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi, Dan!
Thank You.

It's currently the openSUSE packages https://build.opensuse.org/package/show/home:kill_it:JUCE/bitKlavier
And I'd like to send couple PR to simplify Linux builds without modifying sources and .jucer. Is it ok?

**Comment by KottV** [comment]
Hi, there is no more resources available at https://www.dropbox.com/s/tvhad1ecsoycvx6/bK_2.6_installerResources.zip?dl=0 neither http://manyarrowsmusic.com/bitKlavier/bitKlavier_ModelB/bitKlavier_resources.zip

**Comment by dantrueman** [comment]
Apologies, broken link! the link has now been updated, and we'll try to keep it more stable/updated going forward.

https://www.dropbox.com/s/az0o1b3lpz9huvg/Resources.zip?dl=0
