### ISSUE TITLE
MTS client issue - does not play correct scale

### ISSUE THREAD

**Issue by tank-trax** [Princeton-CDH/bitKlavier#140]
bitKlavier 3.3 built from source on Linux Mint 21.1

MTS-ESP Source works as expected
if we load an SCL and/or KBM
bitKlaiver plays the correct notes
using the latest development build of Surge XT, which has both MTS Source and Client support, and it will play the correct scale if active as MTS client, same for Dexed, OB-XD and all other synths that have MTS Client capabilities

however, if bitKlavier is set to be the MTS Client it does not playing the correct notes if either Surge XT or Entonal Studio are enabled as MTS Source

**Comment by tank-trax** [comment]
I also noticed a typo [here](https://github.com/Princeton-CDH/bitKlavier/blob/521b4319cd83b74e23e3d29c279e992f933396f7/bk_JUCE/bitKlavier/Source/Tuning.cpp#L176) 

```
DBG("MAster Midinote: "+String(midiNoteNumber) + "New MidiNote: " + String(midiNoteNumber + lastNoteOffset));
```

**Comment by tank-trax** [comment]
This issue persists, bitKlavier-3.4 can act as MTS Master and other MTS Clients will correctly play the tuning that is loaded as SCL/KBM, however as MTS Client plays incorrect notes/frequencies.

**Comment by dantrueman** [comment]
apologies, missed this first report. the fix is up now.

**Comment by tank-trax** [comment]
I just built the latest commit and it looks to be fixed.

Thanks!!!

@dantrueman could you possibly provide an ETA on when this will be implemented in a binary release?

**Comment by tank-trax** [comment]
@dantrueman could you possibly provide an ETA on when this will be implemented in a binary release?

**Comment by dantrueman** [comment]
Tis already part of the Mac binary release 3.42 here<https://manyarrowsmusic.com/bitKlavier/bitKlavier_3.42_OSX.zip>, Win releasing coming soon.

Thanks,
Dan

From: tank-trax ***@***.***>
Date: Sunday, January 21, 2024 at 10:07 PM
To: Princeton-CDH/bitKlavier ***@***.***>
Cc: Daniel L. Trueman ***@***.***>, Mention ***@***.***>
Subject: Re: [Princeton-CDH/bitKlavier] MTS client issue - does not play correct scale (Issue #140)

@dantrueman<https://github.com/dantrueman> could you possibly provide an ETA on when this will be implemented in a binary release?

**Comment by tank-trax** [comment]
> Tis already part of the Mac binary release 3.42 here
Win releasing coming soon. 
Thanks, Dan

Please let me know when Windows binary will be released.

**Comment by dantrueman** [comment]
Tis up: https://manyarrowsmusic.com/bitKlavier/bitKlavier_3.42_Win.zip

From: tank-trax ***@***.***>
Date: Sunday, January 21, 2024 at 10:26 PM
To: Princeton-CDH/bitKlavier ***@***.***>
Cc: Daniel L. Trueman ***@***.***>, Mention ***@***.***>
Subject: Re: [Princeton-CDH/bitKlavier] MTS client issue - does not play correct scale (Issue #140)

Tis already part of the Mac binary release 3.42 here
Win releasing coming soon.
Thanks, Dan

Please let me know when Windows binary will be released.
