### ISSUE TITLE
Reset does not update UI while preparation view is open

### ISSUE THREAD

**Issue by mulshine** [Princeton-CDH/bitKlavier#57]
### Platform/OS 
10.12.2

### bitKlavier version number
0.0.1.b1

### Format and (if applicable) host
standalone

### Expected Behavior
Reset should update UI when preparation view is open

### Actual Behavior
No change in UI when Reset is performed

### Steps to Reproduce Behavior
Create a modification and reset on a prep, open the prep view, enact the modification (UI changes), enact the reset (UI does not change)

**Comment by mulshine** [comment]
Really? seriously thought I solved this!

**Comment by dantrueman** [comment]
oh, maybe you did, but it was still open and i accidentally closed it, and then reopened it.

On Oct 20, 2017, at 10:16 AM, Mike Mulshine <notifications@github.com<mailto:notifications@github.com>> wrote:

Really? seriously thought I solved this!

**Comment by dantrueman** [comment]
if it’s fixed, can you close it and also add that to the “release 2” draft… ?

;—}

On Oct 20, 2017, at 10:16 AM, Mike Mulshine <notifications@github.com<mailto:notifications@github.com>> wrote:

Really? seriously thought I solved this!
