### ISSUE TITLE
Nostalgic Undertow bug

### ISSUE THREAD

**Issue by dantrueman** [Princeton-CDH/bitKlavier#65]
When undertow value is high and you play high notes, we got loud pops at the ends of the undertow notes; something is wrong with the way notes are shut off if the sample is too short to cover the entire undertow val.

to reproduce: use Nostalgic example 3, set undertow value really high, say 6000, and then play high notes on the piano

**Comment by mulshine** [comment]
@dantrueman I have noticed this as well. This maybe be when undertow is longer than the sample itself?
