### ISSUE TITLE
Set up continuous integration / automated builds with Travis-CI

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/bitKlavier#71]
I think we may be able to adapt from https://github.com/shaduzlabs/audio-plugin-project-template 

See also https://forum.juce.com/t/adding-continuous-integration-support-to-juce-with-travisci/16640

**Comment by rlskoeser** [comment]
I have used travis-ci before and I'm interested in taking a stab at this one, but I don't know how soon I'll be able to get it working.

**Comment by dantrueman** [comment]
cool. i think we need to discuss this further. i don't know a whole lot about CI, but for a team this size and for this particular project, i may need convincing that it's better than the manual and relative frequent integration that we're currently doing. i worry about creating more problems; as it stands now, we sometimes have to integrate carefully...
