### ISSUE TITLE
Update folder structure to match the groups defined in Projucer

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/bitKlavier#72]
The groups in Projucer aren't reflected on the filesystem. I think this is one reason why I was so confused when looking at the code on GitHub: the structure and organization is not visible if you're not looking at the code with Projucer.

From the [JUCE Tutorial: Manage your Projucer project](https://www.juce.com/doc/tutorial_manage_projucer_project):

> Groups are not the same as folders. If you create a file in a group in Projucer, you will also be asked in which folder to save the file. With this, it is possible to have a folder structure that is different from the group structure. However, it is highly recommended and good practice to have your groups follow the structure and names of the folders.

I don't see in the documentation how to move a file once you've added it to the Projucer, but hopefully it won't be too painful.  (If it turns out to be problematic let me know, I may have some ideas.)  You'll probably want to pick a time after you have merge in current feature development so that you don't have to worry about merging changes across files that have changed locations.

**Comment by dantrueman** [comment]
ah..... Mike, am assigning this to you, sorry! ;--}
