### ISSUE TITLE
Negative sustain length (synchronic) can result in clicking

### ISSUE THREAD

**Issue by mulshine** [Princeton-CDH/bitKlavier#92]

**Comment by dantrueman** [comment]
send me a gallery that does this if you can; I can't reproduce it...

**Comment by mulshine** [comment]
will do when i get a chance! i think it might have been when sustain length
was shorter than beat length

**Comment by dantrueman** [comment]
I wonder if it also is related to transposition values other than 1?

**Comment by dantrueman** [comment]
this one pops
[ReleaseStudy_4.xml.zip](https://github.com/Princeton-CDH/bitKlavier/files/1610060/ReleaseStudy_4.xml.zip)

**Comment by dantrueman** [comment]
[SynchronicClickingSimpler.xml.zip](https://github.com/Princeton-CDH/bitKlavier/files/1616634/SynchronicClickingSimpler.xml.zip)
